### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by enricocid** [enricocid/VectorifyDaHome#1]
Could you please help me? @Poussinou, @IzzySoft :)

**Comment by IzzySoft** [comment]
Looks good as far as I can tell. Have you already opened an [RFP](https://gitlab.com/fdroid/rfp/issues)? If not, that would be the first step. Linking the two issues together (mention this issue here with the "author supports inclusion" check box – you'll see what I mean when opening the RFP, and link the RFP here) so one can find the way back-and-forth would be a good idea then.

**Comment by TPS** [comment]
@enricocid, @IzzySoft, @Poussinou:  I don't see that anyone else has yet put in the RFP, so I'd be happy to put it in (via minimal template).  I'll report back when it's submitted.

**Comment by TPS** [comment]
Here y'all go: https://gitlab.com/fdroid/rfp/issues/1073

Btw, @enricocid, you've a typo in the ReadMe: "vaste" → "vast"

**Comment by IzzySoft** [comment]
Thanks @TPS (just please next time leave the description unquoted, makes copying easier :wink:). I've setup metadata and kicked it up for our packagers.

@enricocid what would be optional but highly recommended is setting up Fastlane structures to provide e.g. screenshots. If you use the Fastlane binary for that, you can use the same to deploy to Google Play. With Fastlane, you can manage all metadata inside your repo here: screenshots, summary, description (the latter two even for multiple languages), per-release changelogs etc. One place to rule them all: F-Droid would pick that up automatically, and using the Fastlane binaries you can deploy that to Google Play. For a starter: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

Let us know when you've set that up and have a tag covering it, as then we'd need to remove description and summary from our metadata so yours from Fastlane gets picked up.

**Comment by enricocid** [comment]
Thanks everyone, gonna add fastlane (screenshots and changelogs) asap! 😁

**Comment by enricocid** [comment]
**FASTLANE ADDED!**

**Comment by IzzySoft** [comment]
Thanks! Looks good, will update metadata in the RFP accordingly.

A suggestion, if you permit: imagine people wanting to see the screenshots on their ~5" screens. Your screenshots waste valuable screen estate with that framing then. I'd suggest dropping the frames, they provide no value anyway (especially the area outside the "device frames", though I'd drop the frames completely). Your choice of course – and only my personal opinion :wink:

**Comment by enricocid** [comment]
Done! :)

**Comment by IzzySoft** [comment]
Thanks! Updated screenshots would then be pulled with the next version (as the current tag doesn't cover them; you can of course "move up the tag" – i.e. delete the tag and recreate it – if you think it's worth the effort).

**Comment by enricocid** [comment]
Thanks, gonna release an update/new tag to fix an issue.
Thanks for support, really appreciated 😁👌

**Comment by IzzySoft** [comment]
You're welcome! Just let me know when the new tag is available, and I update metadata once more to reflect that. Though I assume the packager will check and adjust that anyway when processing it, so that metadata update wouldn't be urgent. Cannot hurt. Never hurts to ask (unless one asks for hurt).

**Comment by TPS** [comment]
@enricocid Unless you're hoping to recruit even _more_ help for something here, perhaps remove <kbd>help wanted</kbd>? 🙇🏾‍♂️

**Comment by enricocid** [comment]
@IzzySoft the new tag is available! :)

**Comment by IzzySoft** [comment]
Thanks! Metadata is updated, now we wait for a packager to process the RFP.

**Comment by enricocid** [comment]
The app is now available. Many thanks to everyone :)
