### ISSUE TITLE
Displayed height isn't balanced between blocks when translating

### ISSUE THREAD

**Issue by NathanBnm** [enricocid/VectorifyDaHome#12]
Since the French translation is available the "Vector" box is higher than the "Background" box and this is looking a bit strange. The translated string cannot be compressed and this issue could appear in other languages too, that's why I'm issuing here this. Maybe it would be great to force the two blocks to have the same height.

Here is a screenshot:
![82191228_458385958438679_1555045033239904256_n](https://user-images.githubusercontent.com/45366162/72324885-36ce8380-36ac-11ea-96e1-648056bb050f.png)

**Comment by enricocid** [comment]
try to reduce the text there :) image is enough for the user to understand

**Comment by NathanBnm** [comment]
So you can change it if you want

**Comment by enricocid** [comment]
fixed
