### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by enricocid** [enricocid/VectorifyDaHome#13]
## How to contribute?

I'm opening this issue to ask users to **contribute to translations**. 
This issue will be updated every time new strings will be added. There will be 2 sections:
 - Newly added translations since latest release
 - How to add new translations

## Newly added translations/changelogs since release:

- ### 1.8.0

```
none
```

## How to translate all the strings

1. Download the [strings](https://github.com/enricocid/VectorifyDaHome/blob/master/project/app/src/main/res/values/strings.xml)

2. Edit it using Your preferred editor

3. Send me the file. How?
    - By sending a pull request
    - If you have no idea how to do it just attach the xml here or send it via email specifing the language
    - Don't worry about errors or other shiz, I'm here to assist You if needed

## How to name values-x folder?

To know the country/region **code** check this [link](https://www.iso.org/obp/ui/#search). Select country codes and run Your search. Alpha-2 code is what You need.

- Country language format: values-**x**. x is the country code (lowercase). Examples:
  1. Italian: country code for Italy is **IT**. The folder will be named values-**it**
  2. Hungarian: country code for Hungary is **HU**. The folder will be named values-**hu**

- Regional language format: values-**x-rY**. x is the mother's tongue country code (lowercase) while y is the region code (uppercase). Examples:
  1. Canadian (**CA**) French (**fr**): values-**fr**-r**CA**
  2. Brazilian (**BR**) Portuguese (**pt**): values-**pt**-r**BR**

## What about the PlayStore/F-Droid's listings?

Check the @SpacingBat3 [guide](https://github.com/enricocid/Music-Player-GO/issues/204) for Music Player GO. The same applies to Vectorify da home!

## Contributors

@NathanBnm , @Vistaus , @Jnss98b, @ZJRDroid , @SpacingBat3

Thanks!!! :)

**Comment by Jnss98b** [comment]
I can help with Vietnamese and maybe French

**Comment by NathanBnm** [comment]
I'm already working on French translation 😊

**Comment by Jnss98b** [comment]
That's fine I can just work on the Vietnamese translation then

**Comment by j9o1** [comment]
Strings for Spanish (values-es), there you go
[strings.zip](https://github.com/enricocid/VectorifyDaHome/files/4148690/strings.zip)
Tell me if there's any mistake or sth. 
By the way, maybe you could use https://hosted.weblate.org/

**Comment by enricocid** [comment]
> Strings for Spanish (values-es), there you go
> [strings.zip](https://github.com/enricocid/VectorifyDaHome/files/4148690/strings.zip)
> Tell me if there's any mistake or sth.
> By the way, maybe you could use https://hosted.weblate.org/

Thanks, really appreciated :)
Gonna push the update tomorrow ;)

**Comment by mondstern** [comment]
I would also welcome translations on hosted-weblate :) could then also help with languages. How the pullrequest works, I don't understand.

By the way : this app is so awesome.

**Comment by enricocid** [comment]
> hosted-weblate

I'm evaluating, but if there will be costs then I will continue this way (I don't have a stable job, unfortunately).
To create a pull request:
1. You first need to fork the project
2. Go to main/res and upload the values-xy folder using the browser (You can drag & drop it).
3. Once You have committed this change to Your fork You can click on "pull request" from the main page of the fork and create a pull request (with a proper title).

If you are not sure what to do just upload translated strings here, I will take care of them :)

**Comment by NathanBnm** [comment]
@enricocid I'm familiar with Weblate and this is a really good solution ton automate translations management. It's 100% free as it's maded for open source projects (and open source itself).

**Comment by enricocid** [comment]
> @enricocid I'm familiar with Weblate and this is a really good solution to automate translations management. It's 100% free as it's made for open source projects (and open source itself).

Great, I will contact them and will use it for next updates then :)

**Comment by mondstern** [comment]
@enricocid big thank you if you take weblate 👍

**Comment by NathanBnm** [comment]
> 
> 
> > @enricocid I'm familiar with Weblate and this is a really good solution to automate translations management. It's 100% free as it's made for open source projects (and open source itself).
> 
> Great, I will contact them and will use it for next updates then :)

I think you just have to login with GitHub and associate your project.

**Comment by mondstern** [comment]
I can translate with transifex, crowdin, poeditor and weblate. Weblate is open source and would of course be the best variant, as the previous speakers also wrote. I thank you in advance. greetings from germany.

**Comment by Vistaus** [comment]
I personally like Transifex best, but Weblate or Poeditor would be fine as well. Crowdin sucks for a number of different reasons, but mainly because no matter how much I try, I can't get it to send me email notifications when strings in a project are updated.

**Comment by NathanBnm** [comment]
I didn't have a good experience with Transifex and especially Crowdin for the reasons that @Vistaus mentionned.
I never tried Poeditor before but If heard it was quite good.
I still have a preference for Weblate as it's open source and easy to use.

**Comment by mondstern** [comment]
Yes i say weblate is best

**Comment by enricocid** [comment]
I just sent a request to weblate to add my projects to their platform for free :) I will update You asap

**Comment by enricocid** [comment]
Hey,

so I was able to get enterprise crowdin license for free. You can contribute translations [here](https://enricocid.crowdin.com/vectorify-da-home).
I'm still finishing to setup it, but You should be able to translate. I will update the op as soon as 4.2.0 will be released for public.

(I did not receive any reply from weblate, tho)

**Comment by NathanBnm** [comment]
Same as https://github.com/enricocid/Music-Player-GO/issues/114#issuecomment-590067092

**Comment by enricocid** [comment]
Hello,

So I removed crowdin account for now. I don't like it and the way the project are managed. We need something more simple.
I'm going to contact weblate again :)

edit: gonna clean this thread from old messages if You don't mind

**Comment by enricocid** [comment]
The project is now hosted on weblate:

https://hosted.weblate.org/engage/vectorify-da-home/

Please consider a [donation](https://weblate.org/it/donate/new/) to weblate guys to support their work.

The issue will be closed. :)

**Comment by enricocid** [comment]
Hi guys.
I have never asked for donations as I don't really need.

This time I'm asking to You a little effort.

### **If You liked my work and You want to manifest support for my project please consider to donate to a friend of mine who is living a very difficult situation (lost his job and the home).**

[gofundme page](https://www.gofundme.com/f/aiutarmi-per-favore)

Thanks

**Comment by enricocid** [comment]
Just added few string for accessibility (content descriptions) :)

**Comment by enricocid** [comment]
just added few strings on weblate :)

**Comment by enricocid** [comment]
I've added 2 new strings.
:)

**Comment by enricocid** [comment]
"ok" and "cancel" strings added :)
