### ISSUE TITLE
Changing theme causes the background and vector colors and the vector itself to reset

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/VectorifyDaHome#14]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24306400/73618018-665d1580-45f2-11ea-8545-8c005c45082d.gif)

**Comment by enricocid** [comment]
Let me know if this apk works good for You :)

https://drive.google.com/open?id=1k0usZ5gFoZgznMWa2e1z8V4UEzrA4LGj

**Comment by Jnss98b** [comment]
Yeah that apk doesn't have this problem at all

**Comment by enricocid** [comment]
Thanks, gonna push the update tomorrow :)
