### ISSUE TITLE
[Feature request] Keeps the icon and color preset from the previous session after the app is closed

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/VectorifyDaHome#16]
Right now, once you close the app and open it again, the vector and colors go back to default (New Android logo in black and white)

![ezgif com-resize](https://user-images.githubusercontent.com/24306400/74091466-e61d3100-4a85-11ea-9b04-87eea729970d.gif)

**Comment by enricocid** [comment]
The app actually saves only the latest wallpaper applied. Gonna save the latest setup even if not applied then ;)
