### ISSUE TITLE
Status bar elements have light theme color when the app launches with theme set to automatic and system wide dark mode is enabled

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/VectorifyDaHome#17]
Notice the third time I launch the app with app theme set to automatic, status bar elements are black on dark gray background.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24306400/75503091-b1c0d480-59a2-11ea-8989-5adc5580f347.gif)

**Comment by enricocid** [comment]
Weird, Android 10?

Hope to receive it asap on my mi A2 Lite so I can have a look into this issue (emulator not working anymore on my PC ...). Thanks for reporting 👌😃

**Comment by Jnss98b** [comment]
Yeah it's Android 10 on Pixel 4 XL. Does your app's dark theme not follow battery saver setting on Android 9 and below?

**Comment by enricocid** [comment]
> Yeah it's Android 10 on Pixel 4 XL. Does your app's dark theme not follow battery saver setting on Android 9 and below?

It is following battery saver on < Android 9, like suggested by Google docs:

https://github.com/enricocid/VectorifyDaHome/blob/8347b31b817188025e83c42301b6691376ed8049/project/app/src/main/java/com/iven/vectorify/utils/Utils.kt#L35

For some reasons not depending by me it is not working on some MIUI and Xiaomi devices.

**Comment by Jnss98b** [comment]
Yeah Xiaomi is known for breaking a lot of standard Android behaviors. Isn't the Mi A2 Lite an Android One phone though so it runs near stock Android right?

**Comment by enricocid** [comment]
Yes, it is pure Android with few MIUI integrations (mi services, mi remote, mi feedback). 
I've read on the web that other devs are experiencing this issue on Xiaomi devices. Gonna perform a deeper search about this issue :)

**Comment by enricocid** [comment]
I tried to change the way I'm checking if night mode is enabled. Could You try if this change fixes the issue?

https://drive.google.com/open?id=17ZjAOiFpjg1uCrHeB4KORM1r5e8Tu2vi

**Comment by Jnss98b** [comment]
It doesn't. Also, I just notice I some how fooled the home bar to change color too
![Screenshot_20200301-110735](https://user-images.githubusercontent.com/24306400/75629107-4008a680-5bad-11ea-8670-f03d6b55c16c.png)

**Comment by enricocid** [comment]
Strange, I was able to reproduce and fix this issue on the emulator
Could you try this?

https://drive.google.com/open?id=13ivUWr7_j51dgKHjaczt5qcz62CwKwo-

**Comment by enricocid** [comment]
Another test apk
https://drive.google.com/open?id=1FHWxkMCLaGipiuL9MTyKQd05JE3cQ0Bb

**Comment by Jnss98b** [comment]
Yeah so both of them don't have the bug anymore for me. Thanks for the fix!
