### ISSUE TITLE
[Feature request] Partial or no immersive mode in the vector size and position screen

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/VectorifyDaHome#18]
With Android 10 gestures navigation, the back gesture requires 2 swipes if the home bar is hidden. This is really inconvenient. I think you should either only hide the status bar or don't activate immersive mode at all since the home bar takes up very little space.

![Screenshot_20200301-001223](https://user-images.githubusercontent.com/24306400/75632065-6c7cec80-5bc6-11ea-939f-387020adc000.png)

**Comment by enricocid** [comment]
Hi thanks for the comment but I'm gonna stick with immersive mode + notch adjustments on 👍🏻

**Comment by enricocid** [comment]
Hi, I have added double tap to close to the preview activity :)

**Comment by Jnss98b** [comment]
What did you mean by notch adjustments? Does that mean it will actually fill the display cut out area in immersive mode now?

**Comment by enricocid** [comment]
> What did you mean by notch adjustments? Does that mean it will actually fill the display cut out area in immersive mode now?

Exactly 😉 You can already test it if you want. I have setup actions to automate debug builds. 👍🏻
