### ISSUE TITLE
Adjust Icon Picker size

### ISSUE THREAD

**Issue by stupo** [enricocid/VectorifyDaHome#2]
Hey, great app! Just some thoughts from me for possible optimizing of the used screen space.

It would be great when the available screen space would be used to make the icon picker a bit bigger since there is a lot of blank screen.
The area could then show multiple lines of icons. This would make searching for a specific icon or just strolling through them much better/easier.
Maybe it could be used page-wise? So one initial/last used category will be shown in the picker area and swiping left/right would change the category set.

Any thoughts on this idea?

**Comment by enricocid** [comment]
Yes, you are right. Maybe viewpager will do the trick, but I need some time to think to the redesign.
Thanks for feedback, if you have a sketch don't hesitate to share here. :)

**Comment by enricocid** [comment]
Unfortunately swiping was not possible as it clashes with recycler view ;)

**Comment by stupo** [comment]
Sorry, I didn't have time to answer. 
Just updated the app and I think the usablity got even better now :)
