### ISSUE TITLE
Different images for locked and main screen ?

### ISSUE THREAD

**Issue by MofSeth** [enricocid/VectorifyDaHome#25]
Hello, 
First thank you for your app;
My problem is that i can't set a different image for my locked screen and my curent screen.
Is it a missed feature or did i missed something ?
Thank you for an answer.

**Comment by enricocid** [comment]
It depends by the system's wallpaper picker.
VDH does not apply the wallpaper directly but it does via the system's wallpaper picker.
You could try to save the images (they will be saved to /android/data/com.iven.iconify/files) and apply them using a gallery like photo.

**Comment by MofSeth** [comment]
it works by saving the image and apply them using my gallery app :)
