### ISSUE TITLE
Update the Android robot vector graphic

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/VectorifyDaHome#3]
The android vector in the app has square eyes. You should use the one with circle eyes like with the Android head graphics

![Screenshot_20190902-212947](https://user-images.githubusercontent.com/24306400/64138021-1373fd80-cdc9-11e9-84de-3413ef29cc96.jpg)

**Comment by enricocid** [comment]
Thanks for reporting. Unfortunately I'm still not able to find an updated logo (there are logos from 2014 with rounded eyes but they are different compared to the new one).

If you get a proper svg logo don't hesitate to link here.

**Comment by Jnss98b** [comment]
What new one are we talking about here? The  last one before the Android 10 rebrand? And how different is the one you found from it?

**Comment by enricocid** [comment]
Yes. The head in the ones I've found is bigger and eyes smaller. I can add as an alternative to the one already present...
Anyway, consider that the actual logo comes from official google material icons collection so it is not wrong...

**Comment by Jnss98b** [comment]
How about this one from Wikipedia?
https://upload.wikimedia.org/wikipedia/commons/8/88/Android_Robot_Cleaner.svg

**Comment by enricocid** [comment]
Ok, I can add it.
With it without the Android text? Or both?

**Comment by Jnss98b** [comment]
The svg I linked doesn't have the "android" text though. The image in my comment is just a jpeg.

**Comment by enricocid** [comment]
👌Perfect

**Comment by Jnss98b** [comment]
Actually let me find a newer vector file. The one I linked from Wikipedia seems to be the first flat android robot iteration, not the revised one.

**Comment by Jnss98b** [comment]
You could still add the current one if you want but please add the newer one too if I or someone managed to find the svg for it.

**Comment by Jnss98b** [comment]
[Try this one](https://file.io/t48y2W). It's still not the latest one but it's basically the svg you already have in your app but with round eyes

**Comment by enricocid** [comment]
This one is much better, is it svg (can't understand from mobile)

**Comment by Jnss98b** [comment]
Yep. On mobile you can look at its url or just try to zoom in for a while and see if you can start to see jagged line or not lol

**Comment by enricocid** [comment]
Ok, perfect. Tomorrow will publish the update. Thank You :)

**Comment by Jnss98b** [comment]
That's awesome, thanks!
