### ISSUE TITLE
[Feature request] Add an option for dark mode to respect system theme

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/VectorifyDaHome#7]
Following Google's guidelines at https://developer.android.com/guide/topics/ui/look-and-feel/darktheme
![image](https://user-images.githubusercontent.com/24306400/70771162-1ffbe080-1d3e-11ea-85ea-c86c92898d20.png)

**Comment by enricocid** [comment]
This is already in my to-do list, I already have a working implementation from music player go that already implements this feature in version 4.0.0 I'm going to release within the next days (light, dark and auto, with auto following the system in Android q and battery levels in pre-q).
Unfortunately, as opposed to music player go that does not implement any material component, currently it is not possible to add this option in VDH as DayNight theme is still not available in material components theme, that is the theme I must apply to the app to ensure the correct behaviour of the material component ['app bar: bottom'](https://material.io/components/app-bars-bottom/). The app would crash if I apply Appcompat.DayNight theme.
So we have to wait for DayNight theme to be released in next stable version (can't use alpha or beta releases in the project) of the material components library.

**Comment by enricocid** [comment]
Just to inform You that as soon as I finished with the MPGO update, I will implement day night theme. It will be available very soon ,within this week hopefully :)

**Comment by Jnss98b** [comment]
Thanks for the update! Really appreciate your work

**Comment by enricocid** [comment]
Thanks!
The feature was implemented. I'm gonna release it withun the new 2 days :)
