### ISSUE TITLE
App flashes when opened from background

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/VectorifyDaHome#8]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24306400/70773520-b253b280-1d45-11ea-9d4c-d9be16b681c6.gif)

**Comment by enricocid** [comment]
Thanks. Gonna investigate 🕵🏻‍♂️

**Comment by enricocid** [comment]
With the latest update this problem has gone on my device (Mi A2 lite). Basically I removed some useless code. Let me know if the problem still persists

**Comment by Jnss98b** [comment]
Which update are you mentioning? I'm on version 1.7.1 and the problem still persists

**Comment by enricocid** [comment]
Just released 1.8.0. Let me know if the issue is still there :)

**Comment by Jnss98b** [comment]
Thanks for the info. I will check it out once the update is available to me (damn you play store staged roll out). Right now I'm stuck on 1.7.3

**Comment by Jnss98b** [comment]
It seems to have been fixed
